version: '3.9'

services:
  insurance_db:
    image: lebibop/insurance_db_image
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  insurance_app:
    image: lebibop/insurance_app_image
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - insurance_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://insurance_db:5432/db'